### ISSUE TITLE
give a version number

### ISSUE THREAD

**Issue by SylarMa** [piotr022/UV_K5_playground#11]
Can you give each rssi_sbar, spectrum, rssi_printer a version number, and change it every time you release.

**Comment by SylarMa** [comment]
I don't know what the difference between uv_k5_01_26_rssi_sbar_encoded.bin's release21 and release19 is

**Comment by piotr022** [comment]
good idea :D

**Comment by piotr022** [comment]
okey added it, every new release will have release nr in filename
