### ISSUE TITLE
Display Error

### ISSUE THREAD

**Issue by SylarMa** [piotr022/UV_K5_playground#18]
I am using SBAR, which is very useful, but there is a small issue. On the menu page, sub tone scanning page, etc., when you receive a signal (RX), the SBAR information will be displayed.

A suggestion is to integrate all functions into one mod and select them through the menu.

**Comment by leshniak** [comment]
The second thing is rather impossible due to limited memory.

**Comment by SylarMa** [comment]
> The second thing is rather impossible due to limited memory.

What a pity！

What is the maximum memory？

**Comment by SylarMa** [comment]
57.3kb+2.7kb？

**Comment by Tunas1337** [comment]
Basically, yes. We have whatever memory up to the 60KB limit after the original firmware.

**Comment by piotr022** [comment]
>when you receive a signal (RX), the SBAR information will be displayed.  

this display issue should be fixed in latest release 

>A suggestion is to integrate all functions into one mod and select them through the menu.

thanks to @manujedi we have more space to use, future plan is to merge few mods together

**Comment by SylarMa** [comment]
cool
