### ISSUE TITLE
Release 35 sbar not functional

### ISSUE THREAD

**Issue by kronicd** [piotr022/UV_K5_playground#28]
In release 35 the SBar does not appear after flashing `uv_k5_26_rssi_sbar_encoded_v35.bin`.

I have confirmed that release 34 works properly.

**Comment by tiagofreire-pt** [comment]
I confirm this bug. Re-flashing from v35 and onwards back to v34, works again.

**Comment by piotr022** [comment]
in v35 i have added protection against drawing rssi bar in frequency scan view, it check if original fw draws something on screen at 26th pixels from left on the last display line. Probably that is the issue, i will check it later after finishing views manager

**Comment by kronicd** [comment]
At the moment it doesn't appear in either VFO or Memory mode ([firmware v44](https://github.com/piotr022/UV_K5_playground/releases/download/release-44/uv_k5_26_rssi_sbar_encoded_v44.bin))

https://github.com/piotr022/UV_K5_playground/assets/551541/feb511af-8209-4b1b-a073-0283e23bd4b5

**Comment by piotr022** [comment]
it is probaly caused by this DCS string, please check if disabling DCS on second VFO fixes a problem, if yes i can do steps to fix that

**Comment by kronicd** [comment]
I went to test with and without DCS. As of firmware v48 it works in both cases.

Marking issue as closed as it seems fixed, thankyou for your efforts.

**Comment by tiagofreire-pt** [comment]
Thanks!
