### ISSUE TITLE
Hello UV-K6 Firmware k5_v3.00.10 unable to update

### ISSUE THREAD

**Issue by madd7277727** [piotr022/UV_K5_playground#34]
Any chance of an update to use it?

**Comment by troilus** [comment]
https://github.com/Tunas1337/UV-K5-Modded-Firmwares/issues/40

**Comment by piotr022** [comment]
currently im not going to update original firmware that is wrapped, this requres a lot of reverse engineering work. 
What should be done to update to newer original fw - https://github.com/piotr022/UV_K5_playground/issues/35

**Comment by madd7277727** [comment]
3.00.10 still cannot use uv_k5_XX_rssi_sbar_encoded_v48.bin

**Comment by madd7277727** [comment]
> 目前我不會更新包裝的原始固件，這需要大量的逆向工程工作。 應該怎麼做才能更新到較新的原始固件 - #35

The problem that UV-K6 Firmware k5_v3.00.10 cannot be updated has been solved! Thank you
https://github.com/spm81/Quansheng_UV-K5/tree/main/Firmware/UV-K6
