### ISSUE TITLE
Sbar_v44 shows inproper values related to bars

### ISSUE THREAD

**Issue by pawol** [piotr022/UV_K5_playground#38]
Sbar_v44 shows inproper values related to bars.
The number +20 is displayed earlier +10. I mean that +10 should be earlie rthan +20 when the singal level increases.

**Comment by piotr022** [comment]
hi, very strange, in latest release nothing changes with this part of code and still works fine. Maybe you got some display glitch or your signal just increased to +20. Anyway check latest release
