### ISSUE TITLE
Scanlist symbols lost after RSSI mod.

### ISSUE THREAD

**Issue by santus118** [piotr022/UV_K5_playground#4]
Hello! There is no rhombus symbols now, backing to stock or to "classic" 18-1300 don't brings them back :-(

**Comment by lagidnyj** [comment]
personally, I can't get out of scan mode in any way. I have to turn off the radio

**Comment by piotr022** [comment]
> Hello! There is no rhombus symbols now, backing to stock or to "classic" 18-1300 don't brings them back :-(

Hello, thanks for info, what firmware version did you use before flashing mod? this modification shouldnt affect any other symbols. My mods are basing on 01.26, probably previously you had older version of firmware.

**Comment by piotr022** [comment]
these problem is probably not related with mods
