### ISSUE TITLE
new Quansheng UV-K6 is compatible?

### ISSUE THREAD

**Issue by bialystok** [piotr022/UV_K5_playground#46]
for example https://pl.aliexpress.com/item/1005005691847348.html

Może warto zrobić katalogi dla różnych modeli i jednocześnie udostępnić źródła?

**Comment by lingruby-pl** [comment]
uv-k5 i uv-k5 (8) - uv-k6 to to samo radio tylko w innym opakowaniu i wszystko działa...

uv-k5 and uv-k5 (8) - uv-k6 is the same radio just in a different package and everything works....
