### ISSUE TITLE
New version of FW

### ISSUE THREAD

**Issue by santus118** [piotr022/UV_K5_playground#6]
New version released, can you update it with 3 version and sbar/printer?
https://github.com/amnemonic/Quansheng_UV-K5_Firmware/tree/main/firmware

**Comment by Tomasz-Matuszewski** [comment]
And there is possibility to add inside "s-bar" smalls number like 1 - 3 - 5- 7 - 9  or mark for S9

**Comment by piotr022** [comment]
> And there is possibility to add inside "s-bar" smalls number like 1 - 3 - 5- 7 - 9 or mark for S9  
check the latest release

> New version released, can you update it with 3 version and sbar/printer? https://github.com/amnemonic/Quansheng_UV-K5_Firmware/tree/main/firmware
par_runner is easly upgradable, but i need to get these addresses of symbols located in new firmware, but im not keen on reverse engineering :p
![image](https://github.com/piotr022/UV_K5_playground/assets/17248077/c36ce6d9-c389-4107-8dd0-0cf655fb2294)

**Comment by sparrowhe** [comment]
> > And there is possibility to add inside "s-bar" smalls number like 1 - 3 - 5- 7 - 9 or mark for S9
> 
> check the latest release
> 
> > New version released, can you update it with 3 version and sbar/printer? https://github.com/amnemonic/Quansheng_UV-K5_Firmware/tree/main/firmware
> 
> par_runner is easly upgradable, but i need to get these addresses of symbols located in new firmware, but im not keen on reverse engineering :p ![image](https://user-images.githubusercontent.com/17248077/251306661-c36ce6d9-c389-4107-8dd0-0cf655fb2294.png)

Is there any guideline for get these addresses? I think I can help if you want.

**Comment by piotr022** [comment]
> Is there any guideline for get these addresses? I think I can help if you want.

unfortunetly there is no guide, most of actual functions addressess comes from reverse engineering that was done by @Tunas1337. this process is litle bit complicated you have to find addresses of functions with the same functionality and best with the same singature. For that reason current build stays with that 01_26 firmware.
https://github.com/piotr022/UV_K5_playground/issues/35
