### ISSUE TITLE
Some useful function address mapping for V3 firmware

### ISSUE THREAD

**Issue by tywtyw2002** [piotr022/UV_K5_playground#64]
I did some dig for V3 firmware. 

The address map results for functions in https://github.com/piotr022/UV_K5_playground/blob/main/libs/k5_uv_system/system.hpp are listed below.

```
sub_d4_IRQ_RESET
sub_128_IntDivide
sub_1be4_BK4819ConfigureAndStartTxFsk
sub_8310_PrintFrequency
sub_8454_PrintSmallDigits
sub_8494_PrintTextOnScreen
sub_9fbc_UpdateStatusBar
sub_a128_AdcReadout
sub_a6d4_AirCopyFskSetup
sub_a7e0_BK4819ConfigureAndStartRxFsk
sub_a820_AirCopy72
sub_a914_BK4819SetGpio
sub_a93c_BK4819Reset
sub_aac0_BK4819Read
sub_ac00_BK4819WriteFrequency
sub_ac18_BK4819SetPaGain
sub_affc_BK4819Write
sub_b194_PollKeyboard
sub_b6d4_FlushFramebufferToScreen
sub_b73c_FlushStatusbarBufferToScreen
sub_bcd8_WriteSerialData
sub_bef4_SomeAmStuff
sub_c0e8_IRQ_SYSTICK
sub_c2a0_FormatString
sub_cc8c_DelayMs
sub_cc9c_DelayUs
```

Fonts address https://github.com/amnemonic/Quansheng_UV-K5_Firmware/issues/67

**Comment by tywtyw2002** [comment]
```
.pDisplayBuffer 0x20000648
.pSmallDigs 0xd1a0
.pSmallLeters 0xCED0
.p8FlashLightStatus =  0x200002fb,
.pStatusBarData =  0x200005c8,
.p16Voltage =  0x2000034e,
```

**Comment by rogerclarkmelbourne** [comment]
What are you using to find these addresses e.g. Ghidra, and if so , did you share your Ghidra project somewhere eg. on GitHub

**Comment by rogerclarkmelbourne** [comment]
Thanks

**Comment by tywtyw2002** [comment]
> What are you using to find these addresses e.g. Ghidra, and if so , did you share your Ghidra project somewhere eg. on GitHub

Here is pseudo_c version of v3 firmware(the most functions are decode correctly, but the big data block(ie sound, fonts..) are not decode correctly) and the unzip password is `0x20000648`

You can download at https://0x0.st/H_VI.c.7z , file expires in 7 days.

**Comment by rogerclarkmelbourne** [comment]
OK.

Isn't addres 0x00000000 the vector table for the bootloader ?

**Comment by tywtyw2002** [comment]
The 0x0 from fw.dec.bin is a function, if you unpack the firmware use `qsfirm.py` the program `fw.dec.bin` will not include the bootloader.

I cross reference the v26 functions addresses and the v26 decode, there are match.

<img width="586" alt="Screen Shot 2023-08-09 at 22 07 40 " src="https://github.com/piotr022/UV_K5_playground/assets/576954/10712bbb-8940-4284-a713-b4692946d0e1">

**Comment by rogerclarkmelbourne** [comment]
But even the application code has vector table before the start of its own functions

Possibly your address 0x000000 is actually the code above the application vector table

I would not advise that you decompile a binary that does not contain the vector table, otherwise you can't see how the ISR vectors call into the application

**Comment by tywtyw2002** [comment]
Since most people use Ghidra for RE, I did some rough work for merged binary RE form IDA to Ghidra.

Link https://0x0.st/H_E1.gzf.7z expired in 48hrs.

password is `0x2000034e`

@rogerclarkmelbourne

**Comment by rogerclarkmelbourne** [comment]
Thanks

**Comment by troilus** [comment]
你好，在这个基础上，可以给v3的固件增加“精简版”s表的功能吗？ 我尝试了下精简v26的s表，使其仅仅显示信号强度值，是可以的，并且节约了不少空间

**Comment by tywtyw2002** [comment]
> 你好，在这个基础上，可以给v3的固件增加“精简版”s表的功能吗？ 我尝试了下精简v26的s表，使其仅仅显示信号强度值，是可以的，并且节约了不少空间

Compared to the V2 firmware, the V3 firmware only adds support for Chinese and a new menu style. However, it uses many kbs of ROMs space for displaying the Chinese menu (font and menu title).

Since the open source V2 firmware has already been created, I assume that nobody wants to work on V3.
